name: Pac-Man Commit Animation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy Pac-Man Animation
      run: echo "Aqui você rodaria ou atualizaria sua animação"
